// Essential vehicle brands
export const makes = [
    "Acura",
    "BMW",
    "Chevrolet",
    "Dodge",
    "Ford",
    "Honda",
    "Mazda",
    "Mitsubishi",
    "Nissan",
    "Porsche",
    "Subaru",
    "Toyota",
];

// Extended list of vehicle manufacturers 
export const allMakes = [
    "AMC",
    "Acura",
    "Audi",
    "Autozam",
    "BMW",
    "Bentley",
    "Buick",
    "Cadillac",
    "Checker",
    "Chevrolet",
    "Chrysler",
    "Datsun",
    "Delorean",
    "Dodge",
    "Ducati",
    "Fiat",
    "Ford",
    "GMC",
    "Geo",
    "Honda",
    "Hummer",
    "Hyundai",
    "Indian",
    "Infiniti",
    "International",
    "Isuzu",
    "Jaguar",
    "Jeep",
    "Land Rover",
    "Lexus",
    "Lincoln",
    "Lotus",
    "MG",
    "MINI",
    "Mazda",
    "Mercedes",
    "Mercury",
    "Merkur",
    "Mitsubishi",
    "Nissan",
    "Oldmobile",
    "Oldsmobile",
    "Opel",
    "Plymouth",
    "Pontiac",
    "Porsche",
    "Rolls-Royce",
    "Saab",
    "Saturn",
    "Scion",
    "Sea Doo",
    "Subaru",
    "Suzuki",
    "Toyota",
    "Triumph",
    "Volkswagen",
    "Volvo",
];


export const models = {
    Acura: ["CL", "Integra", "Legend", "NSX", "RSX", "TL", "TSX", "Vigor"],
    BMW: [
        "128i",
        "135i",
        "318",
        "323",
        "325",
        "328",
        "330",
        "335",
        "525",
        "528",
        "530",
        "540",
        "630",
        "633",
        "635",
        "740",
        "750",
        "840",
        "850",
        "M3",
        "M4",
        "M5",
        "M6",
        "Z3",
        "Z4",
    ],
    Chevrolet: [
        "454 SS",
        "Camaro",
        "Cobalt",
        "Colorado",
        "Corvette",
        "HHR",
        "Monte Carlo",
        "Nova",
        "S-10",
        "SS",
        "SSR",
        "Trailblazer",
    ],
    Dodge: [
        "Caravan",
        "Challenger",
        "Charger",
        "Conquest",
        "Dakota",
        "Neon",
        "Power Wagon",
        "Raider",
        "Ram SRT",
        "Rampage",
        "Stealth",
        "Viper",
    ],
    Ford: [
        "Bronco",
        "Contour",
        "Courier",
        "Crown Victoria",
        "Escort",
        "Excursion",
        "Explorer",
        "F-150",
        "F-150 Raptor",
        "F-150 SVT Raptor",
        "F-250",
        "F-350",
        "Festiva",
        "Fiesta",
        "Flex",
        "Focus",
        "Fusion",
        "Lightning",
        "Mustang",
        "Probe",
        "Ranger",
        "Super Duty",
        "Taurus",
    ],
    Honda: [
        "ATC",
        "Accord",
        "Acty",
        "Beat",
        "CB",
        "CBX",
        "CR-V",
        "CRX",
        "CT",
        "Civic",
        "Del Sol",
        "Element",
        "Elite",
        "Express",
        "Fit",
        "Grom",
        "Insight",
        "Odyssey",
        "Prelude",
        "Ridgeline",
        "Ruckus",
        "S2000",
        "Spree",
        "VTX",
        "Z",
    ],
    Mazda: [
        "929",
        "MPV",
        "MX-3",
        "MX-5",
        "MX-6",
        "Mazdaspeed3",
        "Mazdaspeed6",
        "Protege",
        "RX-2",
        "RX-3",
        "RX-4",
        "RX-7",
        "RX-8",
        "Repu",
    ],
    Mitsubishi: ["3000GT", "Eclipse", "Galant", "Lancer", "Montero", "Starion"],
    Nissan: [
        "240SX",
        "300ZX",
        "350Z",
        "370Z",
        "Cefiro",
        "Cube",
        "Frontier",
        "GT-R",
        "Laurel",
        "NX",
        "Pulsar",
        "Sentra",
        "Skyline",
        "Xterra",
    ],
    Porsche: [
        "911",
        "914",
        "924",
        "944",
        "968",
        "Boxster",
        "Cayenne S",
        "Cayman",
    ],
    Subaru: [
        "BRZ",
        "Baja",
        "Forester",
        "Impreza",
        "Legacy",
        "Outback",
        "SVX",
        "WRX",
    ],
    Toyota: [
        "4Runner",
        "86",
        "Camry",
        "Celica",
        "Corolla",
        "Cressida",
        "Land Cruiser",
        "Landcruiser",
        "MR2",
        "Paseo",
        "Rav4",
        "Sera",
        "Starlet",
        "Supra",
        "Tacoma",
        "Tercel",
        "Tundra",
    ],
};
export const generations = {
    Civic: [
        '1988 - 1991',
        '1973 - 1979',
        '1980 - 1983',
        '1984 - 1987',
        '1992 - 1995',
        '1996 - 2000',
        '2001 - 2005',
        '2006 - 2011',
    ],
    Prelude: [
        '1978 - 1987',
        '1988 - 1991',
        '1992 - 1996',
        '1997 - 2002',
    ],
    "240SX": [
        '1989 - 1994',
        '1995 - 1998',
    ]
}
export const chassis = {
    Civic: [
        'Civic 1988-1991 (Civic EF)',
        'Civic 1973-1979 (Civic 1G)',
        'Civic 1980-1983 (2G)',
        'Civic 1984-1987 (3G)',
        'Civic 1992-1995 (EG)',
        'Civic 1996-2000 (EK)',
        'Civic 2001-2005 (EP)',
        'Civic 2006-2011 (8G Si)',
    ],
    Prelude: [
        'Prelude 1978-1987 (Prelude)',
        'Prelude 1988-1991 (Prelude)',
        'Prelude 1992-1996 (Prelude)',
        'Prelude 1997-2002 (Prelude)',
    ]
};